### PR TITLE
Update song.py

### PR DESCRIPTION
**Pull request by Deshdeepak1**
Updated to get home itself. Users won't need to modify '/home/amulya/music'. Using os.path.join instead just adding to strings, it take cares of '/'.

### CODE REVIEW

**Comment by amulyagaur** [comment]
> Updated to get home itself. Users won't need to modify '/home/amulya/music'. Using os.path.join instead just adding to strings, it take cares of '/'.

Thanks for pointing out. Please resolve conflicts and I will merge it.

**Comment by Deshdeepak1** [comment]
Why you replaced request with urllib?

**Comment by amulyagaur** [comment]
> Why you replaced request with urllib?

Will explore it more. Accepted your PR.

**Comment by Deshdeepak1** [comment]
But it is not merged. 
Anyway my 4 PRs are already complete. So no need to add hacktoberfest-accepted label.
Also hacktoberfest is in your topic, so no need to add hacktoberfest-accepted label for anyone, it will be anyway counted.

**Comment by Deshdeepak1** [comment]
#2 Fixed  403 error. It just required adding a reference in header. 
Also improved many parts of code. 
Added formats option.

**Comment by amulyagaur** [comment]
Thanks @Deshdeepak1

**Pull request merged**
